#ifndef CONSTANTS_H
#define CONSTANTS_H

#define LONGUEUR_TETE 40
#define LONGUEUR_FENETRE 1000
#define LARGEUR_FENETRE 800
#define POS_INIT_TETE_X 280
#define POS_INIT_TETE_Y 280


#endif // CONSTANTS_H
